---
proxy_env:
  # put a dummy variable in here when proxy not needed
  stack: lemp
#  http_proxy: http://proxy.example.com:8080
#  https_proxy: https://proxy.example.com:8080

nginx_host: 192.168.51.4
mysql_host: 192.168.52.4

mysqlservice: mysqld
mysql_port: 3306
dbuser: dbuser
dbname: dbtest
upassword: secret