---
- name: install mysql client on all hosts
  hosts: all
  user: ec2-user
  become: yes

  roles:
    - webdocs
    - common

- name: configure and deploy the webservers and application code
  hosts: web
  user: ec2-user
  become: yes

  roles:
    - web

- name: deploy MySQL and configure the databases
  hosts: database
  user: ec2-user
  become: yes

  roles:
    - database