- name: restart nginx
  service: name=nginx state=restarted enable=yes

- name: restart php-fpm
  service: name=php-fpm state=restarted enable=yes

- name: restart redis
  service: name=redis state=restarted enable=yes