---

- name: upgrade all packages
  yum: name=* state=latest

- name: Install MySQL Repo
  yum:
    name: http://repo.mysql.com/mysql-community-release-el7-5.noarch.rpm
    state: present

# Install the packages
- name : Install MySQL Packages
  yum: name={{item}} state=present
  with_items:
    - python-pip
    - python-devel
    - mysql-server
    - mysql-devel
    - MySQL-python
  become: yes

- name: update mysql root password for all root accounts
  mysql_user: name=root host={{ item }} password={{ mysql_root_password }}
  with_items:
   #- "{{ mysql_host }}"
   - 127.0.0.1
   - ::1
   - localhost

- name: copy .my.cnf file with root password credentials
  template: src=root.my dest=/root/.my.cnf owner=root mode=0600

- name: MySQL | Remove the MySQL test database
  mysql_db: db=test state=absent

- name: Delete anonymous MySQL user for localhost.
  mysql_user: name="" state="absent"

- name: create database {{magento_db_name}}
  mysql_db: name={{magento_db_name}} state=present

- name: create user {{ magento_db_user }}
  mysql_user: name={{ magento_db_user }} password={{ magento_db_password }}  priv={{ magento_db_name }}.*:ALL host={{ magento_db_remote_host }} state=present