---
- name: Install Redbox Magento by git
# Example checkout a github repo and use refspec to fetch all pull requests
  git:
    repo: git@bitbucket.org:redbox-digital/projects-nestlewater.git
    dest: /var/www/magento/{{ env }}/
    refspec: '+refs/pull/*:refs/heads/*'

  git:
  repo: git@bitbucket.org:redbox-digital/magento-ee.git
  dest: /var/www/magento/{{ env }}/htdocs
  refspec: '+refs/pull/*:refs/heads/*'
  version: 1.14.2.1
