---
- name: upgrade all packages
  yum: name=* state=latest

# Install the package "mysql"
- yum: name={{item}} state=present
  with_items:
   - mysql-client

- name: Install Epel Repo
  yum:
    name: epel-release
    state: absent

- name: Install Webtatic Repo
  yum:
    name: webtatic-release
    state: present
    enable: yes
