---
- name: upgrade all packages
  dnf: name=* state=latest
  become: yes

# Install the package "mysql"
- name: Install MySQL Client
  dnf: name={{item}} state=present
  with_items:
   - mysql
  become: yes

- name: Install Epel Repo
  dnf:
    name: epel-release
    state: absent
    enablerepo: yes
  become: true

- name: Add multiple repositories into the same file (1/2)
  yum_repository:
    name: webtatic-release
    description: webtatic-release repo
    file: external_repos
    baseurl: https://mirror.webtatic.com/pub/epel/$releasever/webtatic-release.rpm
    gpgcheck: no
  become: true